name: Render Resume and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run render script
        run: npm run render

      - name: Prepare site directory
        run: |
          set -e
          rm -rf site || true
          mkdir -p site
          if [ -f "resume.html" ]; then
            cp resume.html site/index.html
          else
            echo "resume.html not found" >&2
            exit 1
          fi

      - name: Deploy to GitHub Pages (push to gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
