name: Render Resume and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run render script
        run: npm run render

      - name: Prepare site
        run: |
          set -e
          if [ -f "render.html" ]; then
            # ensure index.html exists for Pages
            cp render.html index.html
          else
            echo "render.html not found" >&2
            exit 1
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
